Repository usdot-jpo-ode/jpo-ode, pull requests merged in 2019-05, with the labels that each got.

#341 Add Sonar Code Coverage badge
  README.md
Labels: documentation

#342 Add missing log statements for MessageFrame RSU deposits
  jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/services/asn1/Asn1EncodedDataRouter.java
Labels: missing feature

#348 ODE-1294 Improve readme docs in regards to Sonar/Travis/Maven interaction
  README.md
Labels: documentation

#351 SNMP date format update for firmware change
  jpo-ode-core/src/test/java/us/dot/its/jpo/ode/snmp/SNMPTest.java
  jpo-ode-plugins/src/main/java/us/dot/its/jpo/ode/plugin/SNMP.java
  jpo-ode-svcs/src/test/java/us/dot/its/jpo/ode/snmp/SnmpSessionTest.java
Labels: enhancement, unit tests
